src/Entity/Idea.php
<?php

namespace App\Entity;

use App\Repository\IdeaRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=IdeaRepository::class)
 */
class Idea
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=250)
     * @Assert\NotBlank(message="Le champs title ne doit pas être vide")
     */
    private $Title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $Author;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isPublished;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateCreated;

    /**
     * @var Category
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="ideas")
     */
    private $category;

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param Category $category
     */
    public function setCategory(Category $category): void
    {
        $this->category = $category;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(?string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(?bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->dateCreated;
    }

    public function setDateCreated(?\DateTimeInterface $dateCreated): self
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }
}

src/Form/IdeaType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Idea;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IdeaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title')
            ->add('Description')
            ->add('Author')
            ->add('category', null,[
                    "label" => "Category",
                    "choice_label" => "name"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Idea::class,
        ]);
    }
}

src/Controller/IdeaController.php
<?php

namespace App\Controller;

use App\Entity\Idea;
use App\Form\IdeaType;
use App\Repository\IdeaRepository;
use Doctrine\ORM\EntityManagerInterface;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class IdeaController extends AbstractController
{
    /**
     * @Route("/{_locale}/idea-list", name="idea_list")
     */
    public function list(EntityManagerInterface $em)
    {


        $ideaRepo = $em->getRepository(Idea::class);
        $idea = $ideaRepo->findBy([],["dateCreated" => "DESC"]);
        dump($idea);
        return $this->render('idea/list.html.twig', [
            'controller_name' => 'IdeaController',
            'idea' => $idea
        ]);
    }

    /**
     * @Route("/{_locale}/idea-add", name="idea_add")
     */
    public function add(EntityManagerInterface  $em, Request $request)
    {
        $this->denyAccessUnlessGranted("ROLE_USER");
        $idea = new Idea();
        $ideaForm = $this->createForm(IdeaType::class, $idea);

        $ideaForm->handleRequest($request);
        if($ideaForm->isSubmitted() && $ideaForm->isValid()){

            $em->persist($idea);
            $em->flush();
            $this->addFlash("success", "Idea successfully added!");
            return $this->redirectToRoute("idea_detail", ["id" => $idea->getId()]);
        }

        return $this->render('idea/add.html.twig', [
            'controller_name' => 'IdeaController',
            'ideaForm' => $ideaForm->createView()
        ]);
    }

    /**
     * @Route("/{_locale}/idea-detail/{id}", name="idea_detail")
     */
    public function detail($id, EntityManagerInterface  $em)
    {
        $ideaRepo = $em->getRepository(Idea::class);
        $idea = $ideaRepo->find($id);
        return $this->render('idea/detail.html.twig', [
            'controller_name' => 'IdeaController',
            'idea' => $idea
        ]);
    }
}

templates/idea/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello IdeaController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {{ form_start(ideaForm) }}
    {{ form_widget(ideaForm) }}
    <button type="submit">{{ "Add"|trans }}</button>
    {{ form_end(ideaForm) }}
</div>
{% endblock %}

templates/idea/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello IdeaController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>{{ idea.title }}</h1>
    {% if idea.category is not null %}
        ({{ idea .category.name }})
    {% endif %}
    {{ idea.description }}
    {{ idea.author }}
    {{ idea.dateCreated|date("d/m/Y") }}
</div>
{% endblock %}

templates/idea/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello IdeaController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>{{ "Idea list"|trans }}</h1>
    <ul>
        {% for i in idea %}
            <li><a href="{{ path('idea_detail', {id:i.id}) }}" >{{ i.title }}</a>

                {% if i.category is not null %}
                    ({{ i.category.name }})
                {% endif %}
            </li>
        {% endfor %}
    </ul>


</div>
{% endblock %}